export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_CARD = 'UPDATE_CARD';
export const RESET_USER = 'RESET_USER';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
export const UPDATE_AUTO_RELOAD = 'UPDATE_AUTO_RELOAD';

